# ------------------------------------------------------------------------------
#               NOTE: THIS DOCKERFILE IS GENERATED BY OCI IMAGES PROJECT
#
#                       PLEASE DO NOT EDIT IT DIRECTLY.
# ------------------------------------------------------------------------------
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM registry.access.redhat.com/ubi8/ubi:8.6

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'
ARG MAVEN_VERSION=3.6.3
ARG SHA=c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/3.6.3/binaries

RUN dnf install -y tzdata openssl curl ca-certificates fontconfig glibc-langpack-en gzip tar \
    && dnf update -y; dnf clean all

LABEL name="Builder Cloud Apps Adoptium Temurin OpenJDK11" \
      vendor="Adoptium Temurin OpenJDK11" \
      version="jdk-11.0.16+8" \
      release="11" \
      run="docker run --rm -ti <image_name:tag> -v /workspace/source" \
      summary="Adoptium Temurin OpenJDK11 Docker Image for OpenJDK with hotspot and ubi8" \
      description="For more information on this image please see "
	  
ENV JAVA_VERSION jdk-11.0.16+8

RUN set -eux; \
    ARCH="$(uname -m)"; \
    case "${ARCH}" in \
       aarch64|arm64) \
         ESUM='bb345cabf3e305ff3ce390918d5f69e5cfbced3d9844e0b0531c2690f9ed06ef'; \
         BINARY_URL='https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.16%2B8/OpenJDK11U-jdk_aarch64_linux_hotspot_11.0.16_8.tar.gz'; \
         ;; \
       ppc64el|ppc64le) \
         ESUM='40dea12da26443ad731f9348187b65451711659337e83b6409a2bcf0f057cd2a'; \
         BINARY_URL='https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.16%2B8/OpenJDK11U-jdk_ppc64le_linux_hotspot_11.0.16_8.tar.gz'; \
         ;; \
       amd64|x86_64) \
         ESUM='f79506f80c796d8e6a382f00bd8c528a330c5e29581aaf5cb61e1831742d166f'; \
         BINARY_URL='https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.16%2B8/OpenJDK11U-jdk_x64_linux_hotspot_11.0.16_8.tar.gz'; \
         ;; \
       *) \
         echo "Unsupported arch: ${ARCH}"; \
         exit 1; \
         ;; \
    esac; \
	curl -kLfsSo /tmp/openjdk.tar.gz ${BINARY_URL}; \
    echo "${ESUM} */tmp/openjdk.tar.gz" | sha256sum -c -; \
    mkdir -p /opt/java/openjdk; \
	mkdir -p /opt/maven; \
	mkdir -p /opt/builder; \
    cd /opt/java/openjdk; \
    tar -xf /tmp/openjdk.tar.gz --strip-components=1; \
    rm -rf /tmp/openjdk.tar.gz; \
	mkdir -p /usr/share/maven /usr/share/maven/ref; \
	curl -kfsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz; \
	echo "${SHA}  /tmp/apache-maven.tar.gz" | sha512sum -c -; \
	tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1; \
	rm -f /tmp/apache-maven.tar.gz; \
	ln -s /usr/share/maven/bin/mvn /usr/bin/mvn;

ENV JAVA_HOME=/opt/java/openjdk \
    PATH="/opt/java/openjdk/bin:$PATH"
	ARG BUILD_VERSION=
	ENV MAVEN_HOME=/usr/share/maven
	ENV MAVEN_CONFIG=/opt/maven/.m2	
    ENV MAVEN_CLEAR_REPO="false"
	WORKDIR /workspace/source
	COPY /mvn_builder.sh /opt/builder
	CMD ["/bin/bash","/opt/builder/mvn_builder.sh","run"]